// Mocks generated by Mockito 5.3.0 from annotations
// in wompi_payment_colombia/test/payment_methods/credit_card/credit_card_pay_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wompi_payment_colombia/src/src_exports.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreditCard_0 extends _i1.SmartFake implements _i2.CreditCard {
  _FakeCreditCard_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeWompiClient_1 extends _i1.SmartFake implements _i2.WompiClient {
  _FakeWompiClient_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakePaymentRequestData_2 extends _i1.SmartFake
    implements _i2.PaymentRequestData {
  _FakePaymentRequestData_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCardPaymentResponse_3 extends _i1.SmartFake
    implements _i2.CardPaymentResponse {
  _FakeCardPaymentResponse_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCardResponseData_4 extends _i1.SmartFake
    implements _i2.CardResponseData {
  _FakeCardResponseData_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCardResponseMeta_5 extends _i1.SmartFake
    implements _i2.CardResponseMeta {
  _FakeCardResponseMeta_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [CreditCardPay].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreditCardPay extends _i1.Mock implements _i2.CreditCardPay {
  MockCreditCardPay() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CreditCard get creditCard => (super.noSuchMethod(
          Invocation.getter(#creditCard),
          returnValue: _FakeCreditCard_0(this, Invocation.getter(#creditCard)))
      as _i2.CreditCard);
  @override
  _i2.WompiClient get wompiClient =>
      (super.noSuchMethod(Invocation.getter(#wompiClient),
              returnValue:
                  _FakeWompiClient_1(this, Invocation.getter(#wompiClient)))
          as _i2.WompiClient);
  @override
  _i2.PaymentRequestData get paymentRequest => (super.noSuchMethod(
      Invocation.getter(#paymentRequest),
      returnValue: _FakePaymentRequestData_2(
          this, Invocation.getter(#paymentRequest))) as _i2.PaymentRequestData);
  @override
  _i3.Future<_i2.CardPaymentResponse> pay() => (super.noSuchMethod(
          Invocation.method(#pay, []),
          returnValue: _i3.Future<_i2.CardPaymentResponse>.value(
              _FakeCardPaymentResponse_3(this, Invocation.method(#pay, []))))
      as _i3.Future<_i2.CardPaymentResponse>);
}

/// A class which mocks [CardPaymentResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardPaymentResponse extends _i1.Mock
    implements _i2.CardPaymentResponse {
  MockCardPaymentResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CardResponseData get data => (super.noSuchMethod(Invocation.getter(#data),
          returnValue: _FakeCardResponseData_4(this, Invocation.getter(#data)))
      as _i2.CardResponseData);
  @override
  set data(_i2.CardResponseData? _data) =>
      super.noSuchMethod(Invocation.setter(#data, _data),
          returnValueForMissingStub: null);
  @override
  _i2.CardResponseMeta get meta => (super.noSuchMethod(Invocation.getter(#meta),
          returnValue: _FakeCardResponseMeta_5(this, Invocation.getter(#meta)))
      as _i2.CardResponseMeta);
  @override
  set meta(_i2.CardResponseMeta? _meta) =>
      super.noSuchMethod(Invocation.setter(#meta, _meta),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
